language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nfuser/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nfuser/react-test npm test

after_success:
  - docker build -t nfuser/multi-client ./client
  - docker build -t nfuser/multi-nging ./nginx
  - docker build -t nfuser/multi-server ./server
  - docker build -t nfuser/multi-worker ./worker